#define LOGIN_SUCCESS "\nLogin Successful!\n"



#define INVALID_MENU_CHOICE "It seems you've made an invalid menu choice\nYou'll now be redirected to the main menu ^"
#define SALT_BAE "666"
#define LOGOUT "Logging you out now!!! Good bye!$"



#define LOGIN_ID "Enter your Login ID:"
#define AUTOGEN_PASSWORD "mtech"



#define GET_STUDENT_ID "Enter Student-id: "
#define GET_FACULTY_ID "Enter Faculty id: "
#define GET_COURSE_ID  "Enter Course id: "



#define ADMIN_ADD_STUDENT_AUTOGEN_LOGIN "Student added successfully.\nThe autogenerated login ID for the student is :"
#define ADMIN_ADD_STUDENT_AUTOGEN_PASSWORD "Faculty added successfully.\nThe autogenerated password for student is "



#define ADMIN_ADD_FACULTY_AUTOGEN_LOGIN "The autogenerated login ID for the faculty is :"



#define ENTER_BLOCK_ID "Enter student id to block:"



#define ENTER_ACTIVATE_ID "Enter student id to activate:"




#define ADD_COURSE_NAME "Enter course name: "
#define ADD_COURSE_DEPARTMENT "Enter department: "
#define ADD_COURSE_SEATS "Enter no of seats: "
#define ADD_COURSE_CREDITS "Credits: "
#define ADD_COURSE_SUCCESS "^ Course created successfully!\n The courseid is: "
#define NOT_YOUR_COURSE "This course is not provided by you ^"



#define PASSWORD "\nEnter password #"
#define INVALID_LOGIN "The login ID specified doesn't exist ^"
#define INVALID_PASSWORD "The password specified doesn't match ^"



#define PASSWORD_CHANGE_OLD_PASS "Enter your old password #"
#define PASSWORD_CHANGE_NEW_PASS "\nEnter the new password #"
#define PASSWORD_CHANGE_NEW_PASS_RE "\nReenter the new password #"
#define PASSWORD_CHANGE_SUCCESS "\nPassword changed successfully ^"
#define PASSWORD_CHANGE_NEW_PASS_INVALID "The new password and the reentered passwords don't seem to match ^"
#define PASSWORD_CHANGE_OLD_PASS_INVALID "The entered password doesn't match with the Old password ^"



#define LOG_OUT "You have been logged out ^"

#define ADD_NAME "Enter name: "
#define ADD_AGE "Enter age: "
#define ADD_ADDRESS "Enter address: "
#define ADD_EMAIL "Enter email:"
#define ADD_STUDENT_SUCCESS "Student added successfully!\n"


#define ENTER_DEPARTMENT "Enter department:"
#define ENTER_DESIGNATION "Enter designation:"
#define ADD_FACULTY_SUCCESS "Faculty added successfully!\n"



#define ADMIN_MOD_STUDENT_ID "Enter student-id to modify:"
#define ADMIN_MOD_STUDENT_NEW_NAME "What's the updated value for name?\nName: "
#define ADMIN_MOD_STUDENT_NEW_AGE "What's the updated value for age?\nAge: "
#define ADMIN_MOD_STUDENT_NEW_EMAIL "What's the updated value for email?\nEmail: "
#define ADMIN_MOD_STUDENT_NEW_ADDRESS "What's the updated value for address?\nAddress: "
#define ERRON_INPUT_FOR_NUMBER "It seems you have entered an invalid number!\nYou'll now be redirected to the admin menu ^"
#define ADMIN_MOD_STUDENT_SUCCESS "The required modification was successfully made!\nYou'll now be redirected to the main menu ^"
#define STUDENT_LOGIN_ID_DOESNT_EXIT "student loginid is not valid $"



#define ADMIN_MOD_FACULTY_ID "Enter faculty-id to modify:"
#define ADMIN_MOD_FACULTY_NEW_NAME "What's the updated value for name?\nName: "
#define ADMIN_MOD_FACULTY_NEW_DEPARTMENT "What's the updated value for department?\nDepartment: "
#define ADMIN_MOD_FACULTY_NEW_DESIGNATION "What's the updated value for designation?\nDesignation: "
#define ADMIN_MOD_FACULTY_NEW_EMAIL "What's the updated value for email?\nEmail: "
#define ADMIN_MOD_FACULTY_NEW_ADDRESS "What's the updated value for address?\n Address: "
#define ADMIN_MOD_FACULTY_SUCCESS "The required modification was successfully made!\nYou'll now be redirected to the main menu ^"
#define FACULTY_LOGIN_ID_DOESNT_EXIT "loginid is not valid $"



#define ADD_UNENROLL_SUCCESS "Unenrolled succesfully ^"



#define ADD_ENROLL_SUCCESS "Enrolled successfully ^"



#define MOD_COURSE_ID "Enter course-id to modify: \n"
#define MOD_COURSE_NEW_NAME "What's the updated value for name: "
#define MOD_COURSE_NEW_DEPARTMENT "What's the updated value for department: "
#define MOD_COURSE_NEW_NOOFSEATS "What's the updated value for no of seats: "
#define MOD_COURSE_NEW_CREDITS "What's the updated value for credits: "
#define MOD_COURSE_SUCCESS "The required modification was successfully made\nYou'll now be redirected to the main menu ^"



#define DEL_COURSE_ID "Enter course-id to delete: \n"
#define DEL_COURSE_SUCCESS "Course successfully removed ^"



#define FACULTY_FILE "faculty"
#define STUDENT_FILE "student"
#define COURSE_FILE  "course"
#define ENROLL_FILE "enrollment"



#define INITIAL_PROMPT \
"========== Welcome to IIITB Academia Portal ==========\n" \
"=                                                    =\n" \
"================== Select Your Role ==================\n" \
"=                                                    =\n" \
"=  1.  Admin                                         =\n" \
"=  2.  Faculty                                       =\n" \
"=  3.  Student                                       =\n" \
"=                                                    =\n" \
"======================================================\n" \
"Please enter your choice : "



#define ADMIN_MENU \
"======= You are successfully authenticated !!! =======\n" \
"================= Select the Operation ===============\n" \
"=                                                    =\n" \
"=  1.  Add a Student                                 =\n" \
"=  2.  View Student Details                          =\n" \
"=  3.  Add a Faculty                                 =\n" \
"=  4.  View Faculty Details                          =\n" \
"=  5.  Activate a Student                            =\n" \
"=  6.  Block a Student                               =\n" \
"=  7.  Modify Student Details                        =\n" \
"=  8.  Modify Faculty Details                        =\n" \
"=  9.  Log-Out                                       =\n" \
"=                                                    =\n" \
"======================================================\n" \
"Please enter your choice : "



#define STUDENT_MENU \
"======= You are successfully authenticated !!! =======\n" \
"================= Select the Operation ===============\n" \
"=                                                    =\n" \
"=  1.  View all courses                              =\n" \
"=  2.  Enroll new course                             =\n" \
"=  3.  Drop an enrolled course                       =\n" \
"=  4.  View enrolled courses                         =\n" \
"=  5.  Change password                               =\n" \
"=  6.  Log-Out                                       =\n" \
"=                                                    =\n" \
"======================================================\n" \
"Please enter your choice : "



#define FACULTY_MENU \
"======= You are successfully authenticated !!! =======\n" \
"================= Select the Operation ===============\n" \
"=                                                    =\n" \
"=  1.  View offered courses                          =\n" \
"=  2.  Add new Course                                =\n" \
"=  3.  Remove an offered course                      =\n" \
"=  4.  Change Course Details                         =\n" \
"=  5.  Change password                               =\n" \
"=  6.  Log-Out                                       =\n" \
"=                                                    =\n" \
"======================================================\n" \
"Please enter your choice : "



#define ADMIN_MOD_STUDENT_MENU \
"================= Select the Operation ===============\n" \
"=                                                    =\n" \
"=  1.  Name                                          =\n" \
"=  2.  Age                                           =\n" \
"=  3.  Email Id                                      =\n" \
"=  4.  Address                                       =\n" \
"=                                                    =\n" \
"======================================================\n" \
"::Press any other key to cancel::\n" \
"Please enter your choice : "



#define ADMIN_MOD_FACULTY_MENU \
"================= Select the Operation ===============\n" \
"=                                                    =\n" \
"=  1.  Name                                          =\n" \
"=  2.  Department                                    =\n" \
"=  3.  Designation                                   =\n" \
"=  4.  Email Id                                      =\n" \
"=  5.  Address                                       =\n" \
"=                                                    =\n" \
"======================================================\n" \
"::Press any other key to cancel::\n" \
"Please enter your choice : "



#define MOD_COURSE_MENU \
"================= Select the Operation ===============\n" \
"=                                                    =\n" \
"=  1.  Name                                          =\n" \
"=  2.  Department                                    =\n" \
"=  3.  No Of Seats                                   =\n" \
"=  4.  Credits                                       =\n" \
"=                                                    =\n" \
"======================================================\n" \
"::Press any other key to cancel::\n" \
"Please enter your choice : "
