#ifndef SERVER_CONSTANTS
#define SERVER_CONSTANTS


#define INITIAL_PROMPT "Welcome to VidyaSynergy!!!\nWho are you?\n1. Admin\n2. Faculty\n3. Student\nPress any other number to exit\nEnter the number corresponding to the choice!"

// ========== COMMON TEXT =============================

// LOGIN
#define LOGIN_ID "Enter your login ID"
#define PASSWORD "Enter your password \n# "
#define INVALID_LOGIN "The login ID specified doesn't exist!$"
#define INVALID_PASSWORD "The password specified doesn't match!$"
#define SALT_BAE "666"

// GET ACCOUNT DETAILS
#define GET_ACCOUNT_NUMBER "Enter the account number of the account you're searching for"
#define GET_CUSTOMER_ID "Enter the customer ID of the customer you're searching for:  "

#define GET_FACULTY_ID "Enter the faculty ID of the faculty you're searching for:"

#define ERRON_INPUT_FOR_NUMBER "It seems you have passed a sequence of alphabets when a number was expected or you have entered an invalid number!\nYou'll now be redirected to the main menu!^"

#define INVALID_MENU_CHOICE "It seems you've made an invalid menu choice\nYou'll now be redirected to the main menu!^"

#define CUSTOMER_ID_DOESNT_EXIT "No customer could be found for the given ID"
#define STUDENT_ID_DOESNT_EXIST "No student could be found for the given ID"
#define STUDENT_ID_DOESNT_EXIT "No student could be found for the given ID"
#define CUSTOMER_LOGIN_ID_DOESNT_EXIT "No customer could be found for the given login ID$"
#define CUSTOMER_LOGIN_ID_DOESNT_EXIST "No customer could be found for the given login ID$"

#define FACULTY_ID_DOESNT_EXIT "No faculty could be found for the given login ID$"

#define ACCOUNT_ID_DOESNT_EXIT "No account could be found for the given account number"

#define TRANSACTIONS_NOT_FOUND "No transactions were performed on this account by the customer!^"

// ====================================================

// ========== ADMIN SPECIFIC TEXT======================

// LOGIN WELCOME
#define ADMIN_LOGIN_WELCOME "Welcome dear admin! With great power comes great responsibility!\nEnter your credentials to unlock this power!"
#define ADMIN_LOGIN_SUCCESS "Welcome superman!"

// ADMIN MENU
#define ADMIN_MENU "1. Add Student\n2. Add Faculty\n3. Deactivate Student\n4. Activate Student\n5. Update Student Details\n6. Update Faculty Details\nPress any other key to logout"

// ADD STUDENT
#define ADMIN_ADD_CUSTOMER_PRIMARY "Enter the details for the Student\n"
#define ADMIN_ADD_CUSTOMER_SECONDARY "Enter the details for the secondary customer\n"
#define ADMIN_ADD_CUSTOMER_NAME "What is the Student's name?"
#define ADMIN_ADD_CUSTOMER_GENDER "What is the customer's gender?\nEnter M for male, F for female and O for others"
#define ADMIN_ADD_CUSTOMER_AGE "What is the customer's age?"
#define ADMIN_ADD_CUSTOMER_AUTOGEN_LOGIN "The autogenerated login ID for the customer is : "
#define AUTOGEN_PASSWORD "spookytime" // append to end of next string macro
#define ADMIN_ADD_CUSTOMER_AUTOGEN_PASSWORD "The autogenerated password for the customer is : "
#define ADMIN_ADD_CUSTOMER_WRONG_GENDER "It seems you've enter a wrong gender choice!\nYou'll now be redirected to the main menu!^"


#define ADMIN_LOGOUT "Logging you out now superman! Good bye!$"


// ADD FACULTY
#define ADMIN_ADD_FACULTY "Enter the details for the Faculty\n"
#define ADMIN_ADD_CUSTOMER_SECONDARY "Enter the details for the secondary customer\n"
#define ADMIN_ADD_FACULTY_NAME "What is the Faculty's name?"
#define ADMIN_ADD_FACULTY_GENDER "What is the Faculty's gender?\nEnter M for male, F for female and O for others"
#define ADMIN_ADD_FACULTY_DESIGNATION "What is the designation of the faculty?"
#define ADMIN_ADD_FACULTY_DEPARTMENT "What is the department of the faculty? (Enter EC for Electronics and Communication, CSE for Computer Science, AI for Artificial Intelligence"

#define ADMIN_ADD_FACULTY_AUTOGEN_LOGIN "The autogenerated login ID for the faculty is : "
#define AUTOGEN_PASSWORD "spookytime" // append to end of next string macro
#define ADMIN_ADD_FACULTY_AUTOGEN_PASSWORD "The autogenerated password for the customer is : "
#define ADMIN_ADD_FACULTY_WRONG_GENDER "It seems you've enter a wrong gender choice!\nYou'll now be redirected to the main menu!^"


// ====================================================

// ========== STUDENT SPECIFIC TEXT===================

// LOGIN WELCOME
#define CUSTOMER_LOGIN_WELCOME "Welcome dear Student! Enter your credentials to gain access to your account!"
#define CUSTOMER_LOGIN_SUCCESS "Welcome beloved Student!"

#define CUSTOMER_LOGOUT "Logging you out now dear Student! Good bye!$"

// STUDENT MENU
#define CUSTOMER_MENU "1. Enroll to new Course\n2. Unenroll from Course\n3. View Enrolled Courses\n4. Change Password\nPress any other key to logout"

// ====================================================

// ========== FACULTY SPECIFIC TEXT===================

// LOGIN WELCOME
#define FACULTY_LOGIN_WELCOME "Welcome Respected Faculty! Enter your credentials to gain access to your account!"
#define FACULTY_LOGIN_SUCCESS "Welcome Faculty!" 

#define FACULTY_LOGOUT "Logging you out now Faculty! Good bye!$"

// FACULTY MENU
#define FACULTY_MENU "1. Add new Course\n2. Remove offered Course\n3. View Enrollment in Courses\n4. Change Password\nPress any other key to logout"


#define STUDENT_FILE "./records/student.data"
#define FACULTY_FILE "./records/faculty.data"
#define COURSE_FILE "./records/course.data"

#define ADMIN_MOD_STUDENT_ID "Enter student-id to modify:"
#define ADMIN_MOD_STUDENT_MENU "Which information would you like to modify?\n1.Name \n 2.Age \n 3.Gander \n 4.Email \nPress any other key to cancel"

#define ADMIN_MOD_STUDENT_NEW_NAME "What's the updated value for name?"
#define ADMIN_MOD_STUDENT_NEW_AGE "What's the updated value for age?"
#define ADMIN_MOD_STUDENT_NEW_EMAIL "What's the updated value for email?"
#define ADMIN_MOD_STUDENT_NEW_GENDER "What's the updated value for gender?"
#define ADMIN_MOD_STUDENT_NEW_ADDRESS "What's the updated value for address?"
#define ADMIN_MOD_STUDENT_SUCCESS "The required modification was successfully made!\nYou'll now be redirected to the main menu ^"

#define ADMIN_MOD_FACULTY_ID "Enter faculty-id to modify:"
#define ADMIN_MOD_FACULTY_MENU "Which information would you like to modify?\n1. Name \n 2. Department \n 3. Designation \n 4. Gender \n 5.Email \nPress any other key to cancel"
#define ADMIN_MOD_FACULTY_NEW_NAME "What's the updated value for name?"
#define ADMIN_MOD_FACULTY_NEW_GENDER "What's the updated value for gender?"
#define ADMIN_MOD_FACULTY_NEW_DEPARTMENT "What's the updated value for department?"
#define ADMIN_MOD_FACULTY_NEW_DESIGNATION "What's the updated value for designation?"
#define ADMIN_MOD_FACULTY_NEW_EMAIL "What's the updated value for email?"
#define ADMIN_MOD_FACULTY_SUCCESS "The required modification was successfully made!\nYou'll now be redirected to the main menu ^"

// DEACTIVATE STUDENT
#define ADMIN_DEACTIVATE_STUDENT "What is the STUDENT-ID you want to deactivate?"
#define ADMIN_DEACTIVATE_STUDENT_SUCCESS "This Student has been successfully deactivated\nRedirecting you to the main menu ...^"
#define ADMIN_DEACTIVATE_STUDENT_FAILURE "This Student cannot be deactivated\nRedirecting you to the main menu ...^"


// ACTIVATE STUDENT
#define ADMIN_ACTIVATE_STUDENT "What is the STUDENT-ID you want to activate?"
#define ADMIN_ACTIVATE_STUDENT_SUCCESS "This Student has been successfully activated\nRedirecting you to the main menu ...^"
#define ADMIN_ACTIVATE_STUDENT_FAILURE "This Student cannot be activated\nRedirecting you to the main menu ...^"

// PASSWORD CHANGE
#define PASSWORD_CHANGE_OLD_PASS "Enter your old password"
#define PASSWORD_CHANGE_OLD_PASS_INVALID "The entered password doesn't seem to match with the old password"
#define PASSWORD_CHANGE_NEW_PASS "Enter the new password"
#define PASSWORD_CHANGE_NEW_PASS_RE "Reenter the new password"
#define PASSWORD_CHANGE_NEW_PASS_INVALID "The new password and the reentered passwords don't seem to pass!^"
#define PASSWORD_CHANGE_SUCCESS "Password successfully changed!^"

// ADD COURSE
#define ADD_COURSE_NAME "Enter course name:"
#define ADD_COURSE_DEPARTMENT "Enter department:"
#define ADD_COURSE_SEATS "Enter no of seats:"
#define ADD_COURSE_CREDITS "Credits:"
#define ADD_COURSE_SUCCESS "^ Course created successfully!\n The courseid is "
#endif
